### ISSUE TITLE
To-do list: overall across the pipeline

### ISSUE THREAD

**Issue by gauravsk** [limey-bean/Anacapa#22]
## Overall
 - [x] improve file structures
 - [x] rename the script files according to their step number (e.g. 01-clean-data, ...)

**Comment by gauravsk** [comment]
- [ ] Add some fastq checking steps (maybe https://genome.sph.umich.edu/wiki/FastQValidator ?)
- [ ] Maybe- add a step that verifies that the user has picked the right sequencer type? (e.g. hi-seq vs. mi-seq, maybe https://github.com/10XGenomics/supernova/blob/b82c3d8efa68bda2d95f30621cd6d91308ce11a2/tenkit/lib/python/tenkit/illumina_instrument.py)
