### ISSUE TITLE
To-do list- data cleaning step

### ISSUE THREAD

**Issue by gauravsk** [limey-bean/Anacapa#7]
## Data cleaning 
 - [ ] check if user has periods in file names; break script if so and ask user to rename files
 - [x] rewrite the perl script into python; make it put all of the cleaned output files into a new folder

**Comment by limey-bean** [comment]
that would be rad!

**Comment by gauravsk** [comment]
This may help with converting check_paired.pl to python: https://github.com/enormandeau/Scripts/blob/master/fastqCombinePairedEnd.py

**Comment by limey-bean** [comment]
I like it, the only issue is that it makes a single unpaired reads file.  Would it be hard to make two unpaired reads files (F and R)?

**Comment by gauravsk** [comment]
Oh, yeah, didn't mean to suggest that as a final version, more a note to self for me to look at how this script does it when I write one to our needs.

**Comment by limey-bean** [comment]
Cool cool, It is a good template.

**Comment by gauravsk** [comment]
- [ ] The `QC` folder is emptied out by the end of the full run-- need to figure out where, exactly, and maybe also remove the directory itself (right now the directory is kept, but it is empty). Alternatively, maybe add an option to allow users to retain the QC'd stuff if they want to keep it.

**Comment by gauravsk** [comment]
- [ ] Get rid of the line that generates the error `QC/cutadapt_fastq/primer_sort/*_*_Paired_1.fastq not found` in every run
