### ISSUE TITLE
To-do list: Dada2 step

### ISSUE THREAD

**Issue by gauravsk** [limey-bean/Anacapa#8]
## Summary stats
 - [x] how many sequences were kept/discarded at each step?
 - [ ] what is the average sequence length (or sequence length distribution)?
 - [x] how many sequences were left unpaired,

 - [x] `filterAndTrim()` issue: 

I get the following error running `filterAndTrim()` with the parameters as currently defined:

```
Error in (function (fn, fout, maxN = c(0, 0), truncQ = c(2, 2), truncLen = c(0,  : [...]
Mismatched forward and reverse sequence files: 9587, 9588.
```
I get this because after the first round of cutadapt filtering, I have a slightly different number of sequences left in the forward and reverse files. I might be doing something different in my cutadapt runs, though, than what is in the pipeline now...

```
wc -l 740_2016_S70_L001_R*
   438348 740_2016_S70_L001_R1_001_cut.fastq
   438352 740_2016_S70_L001_R2_001_cut.fastq
```

I can get `filterAndTrim()` to run by setting `matchIDs = TRUE`- with this option, the function checks the header of each sequence rather than assuming they match up. 

Either way, I think it can't hurt to set `matchIDs = TRUE`- just to have an extra check in place. Emily?

**Comment by limey-bean** [comment]
So are you not running the second round of cut adapt?  I use a perl script to sort through the stuff that is paired and the stuff that is now an orphan F or R after sorting by primer (in the second round).

**Comment by limey-bean** [comment]
I am all for extra checks

**Comment by gauravsk** [comment]
- [x] We need to filter out singleton ASVs (those that comprise only 1 read) at the end of the dada2 step (or at least add it as a user-controlled option)
